<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class LaguTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('lagu')->insert([
            [
                'judul' => "Hari Bersamanya",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Bait Pertama",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Kamus Hidupku",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Perfect Time",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Berlayar dengan ku",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Hari Bersamanya",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "On the Phone",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Hujan Turun",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Pasti ku bisa",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Have Fun",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2011",
                'album_id' => "1",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Sampai Jumpa",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Musim yang baik",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Belum",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Lapang Dada",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Beruntungnya Aku",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "My Lovely",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Canggung",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Buka Mata dan Telinga",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Satu Langkah",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
              [
                'judul' => "Selamat Datang",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Sampai Jumpa",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2014",
                'album_id' => "2",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Sahabat Sejati",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Bila Kau tak disamping ku",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Shepia",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Just For My Mom",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Sebuah Kisah Klasik",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Temani Aku",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Pagi yang menakjubkan",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Lihat Dengar Rasakan",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Tunggu Aku Dijakarta",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Karena aku Setia",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Tunjuk satu bintang",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
             [
                'judul' => "Selamat Tidur",
                'artist' => "Sheila on 7",
                'genre' => "Pop",
                'tahun' => "2000",
                'album_id' => "3",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]
        ]);
    }
}
